CREATE SCHEMA IF NOT EXISTS jsf;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS jsf.TB_USER
(
    id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    name varchar(200),
    email varchar(255) unique NOT NULL,
    password varchar(255) NOT NULL

);

CREATE TABLE IF NOT EXISTS jsf.TB_ROLE
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name varchar(255) NOT null,
    CONSTRAINT tb_role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS jsf.TB_USER_ROLE (
	user_id uuid NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT tb_user_role_pkey PRIMARY KEY (user_id, role_id)
);

-- users.tb_user_role foreign keys
ALTER TABLE jsf.TB_USER_ROLE ADD FOREIGN KEY (user_id) REFERENCES jsf.TB_USER(id);
ALTER TABLE jsf.TB_USER_ROLE ADD FOREIGN KEY (role_id) REFERENCES jsf.TB_ROLE(id);


INSERT INTO jsf.TB_ROLE (role_name) VALUES
	 ('ROLE_OPERATOR'),
	 ('ROLE_ADMIN');

INSERT INTO jsf.TB_USER (id, email,"name","password") VALUES
	 ('1728d3f6-9282-4021-b186-4d458bdbc038', 'admin@jsf.com','Administrador','$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu'),
	 ('2af448b1-a8b4-403e-8405-2c085f8fe0b6', 'sub_admin@jsf.com','Sub','$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu'),
	 ('73d26316-2ecf-4bec-9cb9-c334be24ccbf', 'test','Common','$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu');

INSERT INTO jsf.TB_USER_ROLE (user_id,role_id) VALUES
	 ('1728d3f6-9282-4021-b186-4d458bdbc038',1),
	 ('1728d3f6-9282-4021-b186-4d458bdbc038',2),
	 ('2af448b1-a8b4-403e-8405-2c085f8fe0b6',1),
	 ('2af448b1-a8b4-403e-8405-2c085f8fe0b6',2),
	 ('73d26316-2ecf-4bec-9cb9-c334be24ccbf',1);

CREATE TABLE jsf.tb_pessoa (
	id bigserial NOT NULL,
	cpf varchar(255) NULL,
	datanascimento date NULL,
	funcionario bool NULL,
	nome varchar(255) NULL,
	CONSTRAINT tb_pessoa_pkey PRIMARY KEY (id)
);

CREATE TABLE jsf.tb_projeto (
	id bigserial NOT NULL,
	data_fim date NULL,
	data_inicio date NULL,
	data_previsao_fim date NULL,
	descricao text NULL,
	idgerente int8 NOT NULL,
	nome varchar(255) NULL,
	orcamento float8 NOT NULL,
	risco varchar(255) NULL,
	status int4 NULL,
	CONSTRAINT tb_projeto_pkey PRIMARY KEY (id)
);

CREATE TABLE jsf.tb_membros (
	idprojeto int8 NOT NULL,
	idpessoa int8 NOT NULL
);

-- jsf.tb_membros foreign keys

ALTER TABLE jsf.tb_membros ADD FOREIGN KEY (idpessoa) REFERENCES jsf.tb_pessoa(id);
ALTER TABLE jsf.tb_membros ADD FOREIGN KEY (idprojeto) REFERENCES jsf.tb_projeto(id);
